server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true